### ISSUE TITLE
Minor: Duplicate additional_data method 

### ISSUE THREAD

**Issue by forsbergplustwo** [baoagency/polaris-view-components#2]
https://github.com/baoagency/polaris-view-components/blob/40df8cbaa278574a33730bf5b827c9b171948c2c/app/components/application_component.rb#L22

Method is repeated twice in ApplicationComponent 😉

This repo is 🔥🔥🔥 Well done!

**Comment by dan-gamble** [comment]
Thanks Björn 😊

There's an `additional_data` and `additional_aria`. I think you may have misread them 🤓

Hoping to do some more additions to this over the weekend. If you are interested in using but feeling like you can't because of some missing components then give me a shout!

**Comment by forsbergplustwo** [comment]
I’m an idiot, even double checked! 🤷‍♂️ We’ve got our own internal repo going which is similar but I love how you’ve gone all in on doing things 1-1 vs Shopify. Should have just waited a few months and used yours 😅

**Comment by dan-gamble** [comment]
Ha!

My goal is to effectively replicate Polaris. I doubt I'll be able to do it 100% but will definitely get all of the main components and most of everything else. I Will likely just miss the very low-used ones.

Things like Dropzone and Popover are really hard to replicate serverside but I'm happy with how the Dropzone turned out!
